name: "Deploy velero"

on:
  workflow_dispatch:

jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az aks get-credentials --resource-group my-aks-cluster-rg --name my-aks-cluster-primary
          wget https://github.com/vmware-tanzu/velero/releases/download/v1.10.2/velero-v1.10.2-linux-amd64.tar.gz
          tar -zxvf velero-v1.10.2-linux-amd64.tar.gz
          cd velero-v1.10.2-linux-amd64
          echo "${{ secrets.GCP_CREDENTIALS }}" > credentials-velero.json
          cat credentials-velero.json
          ./velero install --plugins velero/velero-plugin-for-gcp:v1.6.0,velero/velero-plugin-for-csi:v0.4.2,velero/velero-plugin-for-microsoft-azure:v1.6.0 --use-node-agent --features=enableCSI --provider gcp --uploader-type restic --bucket 'shagok-velero-backup' --secret-file ./credentials-velero.json --use-volume-snapshots=false
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          cat << EOF > storage-class-gcp.yml
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: standard-rwo
          provisioner: kubernetes.io/azure-disk
          parameters:
            storageaccounttype: Standard_LRS
            kind: Managed
            cachingmode: ReadOnly
          EOF
          chmod +x kubectl
          set +e
          ./kubectl create -f storage-class-gcp.yml
          set -e
